name: Check for broken links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  check-for-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install -g linkinator
      - run: linkinator -r https://writings.flashbots.net/
